### ISSUE TITLE
SUGGESTION: Ability to use this plugin directly in a sampGDK gamemode (?)

### ISSUE THREAD

**Issue by IstuntmanI** [Y-Less/fixes-plugin#2]
Hey, we talked about this before. Is there the ability to use it directly in a sampGDK gamemode ? We should be able to just paste some source files in our gamemode's files and run correctly while only including a header for the declarations. I see that you are also using the log core plugin, which adds an additional dependency for the server (logcore.so in the same folder as samp-server). When I had to use MySQL in the sampGDK gamemode the most problems it had with the logcore plugin, because it used way too many AMX functions inside which were buggy with a sampGDK plugin, the server was crashing (if I remember correctly, or memory leaking A LOT) when any kind of debugging was enabled.

This is necessary for custom functions and old bad functions added by this plugin, for the native functions that are just fixed I think that the AMX redirect would make its job if this plugin is loaded before the server plugin.

It would be great if this would be possible easily. It should provide a ```Fixes``` namespace for every custom/native-hooked function and hooked callback.
For any sampGDK/sampSDK callback function we should have an even deeper namespace called ```Fixes::Internal``` or something like that, so we could put ```Fixes::Internal::Load``` under our ```Load``` function (of course, other necessary callbacks too). Not sure about all callbacks used in this plugin, we would have to add every single one of them under our callbacks, I don't have any easier idea about this right now. Adding all these tons of callbacks would be a pretty long setup. Maybe they could be hooked under ```OnPublicCall``` with string hashing (to make the comparations faster, with a ```switch```) and just add ```Fixes::Internal::OnPublicCall``` under our ```OnPublicCall``` callback, but this would require pretty much more code in this plugin I think.

I wonder if Kalcor could give us a better and more direct interface for C/++ gamemode developing, the compatibility between sampGDK and other plugins really sucks right now. Pawn is terrible (but it actually has some advantages compared to C++ [and a lot more compared to C], can't remember exactly what advantages, but "0b" binary prefixing was one of them, but it was added in C++14).

If you can't make or don't want to add this I understand, it's pretty hard with all those hooks (as C++ doesn't have any hooking without memory addresses, probably because of security).

This whole fixing bugged things in a reliable way is quite a challenge. I have to thank you again for all you did for SA-MP.

-------

Also, I see that you created one test fix: ```SetPlayerPos```, which is in a .cpp with the name of the function. Wouldn't it be better if all fixes would be in a single file ? It would compile fast anyway. Or, at least, it should contain more fixes of one type in a file. Fixes that aren't requiring any other variable could be in a ```fixes/simple.cpp``` (bad name) file, while more complex ones like ```PassengerSeating``` should have their own files with all the hooking made there (hooking is harder with independent files).

**Comment by Y-Less** [comment]
OK, that seems like about 7 different issues in one, so I'll try answer them all:

1. Using this directly.  I've actually mostly enabled this already, by (half accidentally) writing a generic system for defining natives, you can just do:

```cpp
// In your header:
NATIVE_DEFN(SetPlayerPosAndAngle, bool(int playerid, float x, float y, float z, float a));

// In your code:
NATIVE_DECL(SetPlayerPosAndAngle, bool(int playerid, float x, float y, float z, float a))
{
	// Implementation here...
	SetPlayerPos(playerid, x, y, z);
	return SetPlayerFacingAngle(playerid, a);
}
```

That example is already in the code, just as a test.  You don't even need to do anything else to add the native to the AMX, it is done via global object static initialisation.  You can either just use that as a normal PAWN function, and could access it via sampgdk, or more directly by adding this to your plugin:

```cpp
PLUGIN_NATIVE(SetPlayerPosAndAngle, bool(int playerid, float x, float y, float z, float a));
```

That will create an import symbol to access the native directly.  You might also notice that there is no mention there of `AMX * amx, cell * params` - all the casting is done automatically by a wrapper (which is bypassed when using the import from another plugin).  I'll write more about that later if I can be bothered, but they can be accessed (they will both be NULL if called from a plugin), and you can do varargs as well.

2. I'm not using AMX redirects - they are too order dependent, instead I'm using subhook redirects, which are much lower-level.

3. Namespaces I'm still playing about with - I'm thinking of making the import/export/hook/natives thing I wrote a separate library so that any plugin can declare their natives quickly and export them.  Possibly change it to use namespaces as:

```cpp
NATIVE_DEFN(fixes, SetPlayerPosAndAngle, bool(int playerid, float x, float y, float z, float a));
```

4. Can you expand on the logcore problems please?  I've not used it much, but it seemed like a good solution (assuming it worked) for compatability with other plugins.

5. No.  One of my least favourite things about the PAWN fixes include was the use of a single file.  There was a good reason for it and it couldn't be changed: it made download and inclusion very easy - just get one file and you are done, which was important.  However, it made the code horrible.  This is not a multiple-million line project, there is no need to worry about compile times, which will be sub-one-second.  I'm currently more worried about server startup time, loading this plugin seems to stall the server for about 20 seconds (but I've got a feeling that's actually caused by my AV not liking the fact that a .dll is constantly changing and doing strange things with code manipulation, so shouldn't be a problem for release).

6. I'm not sure what you're talking about with the callbacks.  If you were using this from another plugin, you wouldn't need to call them directly, since sampgdk would take care of that.  If you are talking about within this plugin, the callbacks aren't really `Internal`, since they are a vital part of the plugin itself.

7. Kalcor isn't going to do anything, but I'm quite happy with my new solution for hooking, declaring, and calling natives.  You can also hook them in an almost identical way to the code for declaring them above:

```cpp
// In your header:
HOOK_DEFN(SetPlayerPos, bool(int playerid, float x, float y, float z));

// In your code:
HOOK_DECL(SetPlayerPos, bool(int playerid, float x, float y, float z))
{
	// Implementation here...
	return SetPlayerPos(playerid, x, y, z + 6.6);
}
```

I have just realised that `DEFN` and `DECL` are the wrong way round though - the definition is declaring it, and the declaration is defining it.  You can also use the exact same method for importing this hook in to another plugin and calling it directly:

```cpp
PLUGIN_NATIVE(SetPlayerPos, bool(int playerid, float x, float y, float z));
```

Using the same macro for importing both natives and hooks is important - it means that the author of the other plugin doesn't need to worry about which it is (or know which, or care if it changes).  Currently that import has no namespace, but I'll fix that as I wrote above.
